### ISSUE TITLE
FIPS Compliant Encryption Out-EncryptedScript

### ISSUE THREAD

**Issue by aconite33** [mattifestation/PowerSploit#60]
During a Red Team Op, we stumbled upon this:
If the Windows Machine has the [FIPS compliance setting configured](http://blog.aggregatedintelligence.com/2007/10/fips-validated-cryptographic-algorithms.html) , the encrypted script will not run due to the encryption algorithm being used is not allowed on the system.

However, I was able to fix this by changing the encryption algorithm to a FIPS compliant. I used Triple DES and I was able to encrypt, decrypt, and execute the script.

These four lines are what I changed:
85: $Key = New-Object System.Security.Cryptography.TripleDESCryptoServiceProvider
...
87: [Byte[]] $KeyBytes = $DerivedPass.GetBytes(16)
...
110:[Byte[]] $e = $derivedPass.GetBytes(16);
111: $f = New-Object System.Security.Cryptography.TripleDESCryptoServiceProvider;

**Comment by mattifestation** [comment]
Thanks for bringing this to my attention and sorry for the delay in responding. I'd be more comfortable sticking to an AES crypto algorithm. Not being familiar with FIPS compliance settings, do you know if the System.Security.Cryptography.AesManaged class would be an acceptable alternative or is that essentially the same thing?

Thanks,
Matt

**Comment by aconite33** [comment]
Matt,

I used System.Security.Cryptography.RijndaelManaged, however I'm sure the AESManaged would work as well.
You can test it by modifying this registry entry: HKLM\System\CurrentControlSet\Control\Lsa\FIPSAlgorithmPolicy DWORD : Enabled 1
(http://blog.aggregatedintelligence.com/2007/10/fips-validated-cryptographic-algorithms.html)

AES is a FIPS compliant encryption according to this document: http://csrc.nist.gov/publications/fips/fips197/fips-197.pdf

**Comment by mattifestation** [comment]
AESManaged didn't work so I changed it to TripleDESCryptoServiceProvider. Thanks for the suggestion! In my testing, when I enabled FIPSAlgorithmPolicy, it broke git when I tried to commit. LOL.

I also cleaned up the script a bit. It still needs some refactoring though. That thing is ugly! ;) It was one of my first scripts though. Haha.
